"""Update password length

Revision ID: 1baeab92a2cc
Revises: 37b9654f5aac
Create Date: 2025-09-17 17:45:09.088674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1baeab92a2cc'
down_revision = '37b9654f5aac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("enterprise", "password",
        existing_type=sa.String(length=30),
        type_=sa.String(length=255),
        existing_nullable=False
    )
    op.alter_column("users", "password",
        existing_type=sa.String(length=30),
        type_=sa.String(length=255),
        existing_nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("enterprise", "password",
        existing_type=sa.String(length=255),
        type_=sa.String(length=30),
        existing_nullable=False
    )
    op.alter_column("users", "password",
        existing_type=sa.String(length=255),
        type_=sa.String(length=30),
        existing_nullable=False
    )
    # ### end Alembic commands ###
