"""detect users and enterprise tables

Revision ID: 37b9654f5aac
Revises: 73b8a35c6ba2
Create Date: 2025-09-16 13:05:24.474864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b9654f5aac'
down_revision = '73b8a35c6ba2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
